name: Build and Deploy ASP.Net Core App

env:
  PACKAGE_PATH: '.'
  DOTNET_VERSION: '9'                   # .NET version
  DEPLOY_PROFILE_SECRET: 'MONSTERASP_PUBLISH_PROFILE'  # اسم الـ secret اللي هتحطه في GitHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish application locally
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Create publish profile from secret
        run: echo "${{ secrets.MONSTERASP_PUBLISH_PROFILE }}" > ./publishprofile.pubxml

      - name: Deploy to MonsterASP using publish profile
        run: |
          dotnet publish ./YourProject.csproj \
            -c Release \
            -o ./publish \
            /p:PublishProfile=./publishprofile.pubxml \
            /p:AllowUntrustedCertificate=true
