name: Build and Deploy ASP.Net Core App

env:
  DOTNET_VERSION: '9'                                # .NET version
  DEPLOY_PROFILE_SECRET: 'MONSTERASP_PUBLISH_PROFILE' # اسم الـ secret اللي هتحطه في GitHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build ./src/Restaurants.API/Restaurants.API.csproj -c Release --no-restore

      - name: Create publish profile from secret
        run: echo "${{ secrets.MONSTERASP_PUBLISH_PROFILE }}" > ./src/Restaurants.API/publishprofile.pubxml

      - name: Publish and Deploy to MonsterASP
        run: |
          dotnet publish ./src/Restaurants.API/Restaurants.API.csproj \
          -c Release \
          -p:PublishProfile=./src/Restaurants.API/publishprofile.pubxml \
          -p:AllowUntrustedCertificate=true
